"""empty message

Revision ID: 10c32a41145b
Revises: 
Create Date: 2024-09-06 08:16:24.322301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10c32a41145b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template',
    sa.Column('templateId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('templateType', sa.Enum('CONTEXT_BASED', 'FROM_SAMPLE_PROBLEM', 'FROM_MORE_EXAMPLES', 'FROM_CONCEPT_COMPARISON', 'REMOVE_AMBIGUITY', 'FIX_REFERENCES', 'FIX_DISTRACTORS'), nullable=False),
    sa.Column('templateName', sa.String(length=255), nullable=False),
    sa.Column('templateVersion', sa.Integer(), nullable=False),
    sa.Column('defaultAssignments', sa.JSON(), nullable=True),
    sa.Column('templateStr', sa.Text(), nullable=True),
    sa.Column('updateMessage', sa.Text(), nullable=True),
    sa.Column('updater', sa.String(length=255), nullable=True),
    sa.Column('updateTime', sa.DateTime(), nullable=True),
    sa.Column('generateQuestionFormat', sa.Enum('SINGLE_CHOICE', 'MULTIPLE_CHOICE', 'FILL_IN_THE_BLANKS', 'TEXT_BASED'), nullable=False),
    sa.PrimaryKeyConstraint('templateId')
    )
    op.create_table('generation',
    sa.Column('generationId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('templateId', sa.Integer(), nullable=False),
    sa.Column('promptText', sa.Text(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('assignment', sa.JSON(), nullable=True),
    sa.Column('gptResponse', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['templateId'], ['template.templateId'], ),
    sa.PrimaryKeyConstraint('generationId')
    )
    op.create_table('question',
    sa.Column('questionId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('generationId', sa.Integer(), nullable=False),
    sa.Column('questionType', sa.String(length=50), nullable=False),
    sa.Column('questionText', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('modificationType', sa.String(length=255), nullable=True),
    sa.Column('templateId', sa.Integer(), nullable=True),
    sa.Column('assignment', sa.JSON(), nullable=True),
    sa.Column('updater', sa.String(length=255), nullable=True),
    sa.Column('updateTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['generationId'], ['generation.generationId'], ),
    sa.ForeignKeyConstraint(['templateId'], ['template.templateId'], ),
    sa.PrimaryKeyConstraint('questionId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    op.drop_table('generation')
    op.drop_table('template')
    # ### end Alembic commands ###
