"""empty message

Revision ID: 17138338c52f
Revises: 360c2ad21146
Create Date: 2024-09-12 21:56:18.670325

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '17138338c52f'
down_revision = '360c2ad21146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modificationType', sa.String(length=255), nullable=True))
        batch_op.drop_column('modification_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modification_type', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('modificationType')

    # ### end Alembic commands ###
