"""Initial migration

Revision ID: ef1133d892d7
Revises: 
Create Date: 2024-08-30 11:49:28.980416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef1133d892d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template',
    sa.Column('template_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_type', sa.Enum('CONTEXT_BASED', 'FROM_SAMPLE_PROBLEM', 'FROM_MORE_EXAMPLES', 'FROM_CONCEPT_COMPARISON', 'REMOVE_AMBIGUITY', 'FIX_REFERENCES', 'FIX_DISTRACTORS'), nullable=False),
    sa.Column('template_name', sa.String(length=255), nullable=False),
    sa.Column('template_version', sa.Integer(), nullable=False),
    sa.Column('default_assignments', sa.JSON(), nullable=True),
    sa.Column('template_str', sa.Text(), nullable=True),
    sa.Column('update_message', sa.Text(), nullable=True),
    sa.Column('updater', sa.String(length=255), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('template_id')
    )
    op.create_table('generation',
    sa.Column('generation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('assignment', sa.JSON(), nullable=True),
    sa.Column('gpt_response', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['template.template_id'], ),
    sa.PrimaryKeyConstraint('generation_id')
    )
    op.create_table('question',
    sa.Column('question_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('generation_id', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.String(length=50), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('modification_type', sa.String(length=255), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('assignment', sa.JSON(), nullable=True),
    sa.Column('updater', sa.String(length=255), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['generation_id'], ['generation.generation_id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['template.template_id'], ),
    sa.PrimaryKeyConstraint('question_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    op.drop_table('generation')
    op.drop_table('template')
    # ### end Alembic commands ###
